services:
  - type: web
    name: smartmeet-ai
    env: python
    runtime: python-3.11.7
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt && python -c 'import nltk; nltk.download(\"punkt\", quiet=True); nltk.download(\"stopwords\", quiet=True)'"
    startCommand: "streamlit run main.py --server.port $PORT --server.address 0.0.0.0 --server.headless true"
    healthCheckPath: /
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: STREAMLIT_SERVER_HEADLESS
        value: true
      - key: STREAMLIT_BROWSER_GATHER_USAGE_STATS
        value: false
      - key: STREAMLIT_THEME_BASE
        value: light
