services:
  - type: web
    name: smartmeet-ai
    env: python
    buildCommand: "pip install -r requirements.txt && python -c 'import nltk; nltk.download(\"punkt\"); nltk.download(\"stopwords\")'"
    startCommand: "streamlit run main.py --server.port $PORT --server.address 0.0.0.0"
    healthCheckPath: /
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: STREAMLIT_SERVER_HEADLESS
        value: true
      - key: STREAMLIT_BROWSER_GATHER_USAGE_STATS
        value: false
